language: c

sudo: false

matrix:
  include:
    - env: LUA="lua 5.1"
      os: linux
    - env: LUA="lua 5.2"
      os: linux
    - env: LUA="lua 5.3"
      os: linux
    - env: LUA="luajit 2.0"
      os: linux
    - env: LUA="luajit 2.1"
      os: linux
    - env: LUA="lua 5.1"
      os: osx
    - env: LUA="lua 5.2"
      os: osx
    - env: LUA="lua 5.3"
      os: osx
    - env: LUA="luajit 2.0"
      os: osx
    - env: LUA="luajit 2.1"
      os: osx

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:~/Library/Python/2.7/bin/; fi
  - pip2 install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate

install:
  - luarocks install lua-llthreads2
  - luarocks install mtmsg
  - luarocks make rockspecs/mtstates-scm-0.rockspec

script: 
  - cd examples
  - lua example01.lua
  - lua example02.lua
  - cd ../tests
  - lua test01.lua

notifications:
  email:
    on_success: change
    on_failure: always
