version: 0.3.2.{build}

os:
- Windows Server 2012 R2

shallow_clone: true

environment:
  LR_EXTERNAL: c:\external

  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"

platform:
  - x64
  - x86
  - mingw

cache:
  - c:\hererocks -> appveyor.yml
  - c:\external -> appveyor.yml

install:
  - echo "Setup..."
  - set PATH=C:\Python27\Scripts;%LR_EXTERNAL%;%PATH%
  - if /I "%platform%"=="x86" set HR_TARGET=vs_32
  - if /I "%platform%"=="x64" set HR_TARGET=vs_64
  - if /I "%platform%"=="mingw" set HR_TARGET=mingw
  - if /I "%platform%"=="mingw" set PATH=C:\MinGW\bin;%PATH%
  - if not exist "%LR_EXTERNAL%" (
      mkdir "%LR_EXTERNAL%" &&
      mkdir "%LR_EXTERNAL%\lib" &&
      mkdir "%LR_EXTERNAL%\include"
    )
  - if not exist c:\hererocks (
      pip install hererocks &&
      hererocks c:\hererocks --%LUA% --target %HR_TARGET% -rlatest
    )
  - call c:\hererocks\bin\activate

before_build:
  # external deps

build_script:
  - echo "Making..."
  - luarocks install lua-llthreads2
  - luarocks install mtmsg
  - luarocks make rockspecs/mtstates-scm-0.rockspec

before_test:
  # test deps

test_script:
  - echo "Testing..."
  - cd %APPVEYOR_BUILD_FOLDER%\examples
  - lua example01.lua
  - lua example02.lua
  - cd %APPVEYOR_BUILD_FOLDER%\tests
  - lua test01.lua

after_test:
  # deploy
