version: 0.3.2.{build}

image: Windows Server 2012 R2

shallow_clone: true

environment:
  LR_EXTERNAL: c:\external

  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"
  - LUA: "lua 5.4"

platform:
  - x64
  - x86
  - mingw

cache:
  - c:\hererocks -> appveyor.yml
  - c:\external -> appveyor.yml



install:
  - echo "Setup..."
  - set PATH=C:\Python38\;C:\Python38\Scripts;%LR_EXTERNAL%;%PATH%
  - where py
  - py --version
  - where python
  - python --version
  - where pip
  - pip --version
  - if /I "%platform%"=="x86" set HR_TARGET=vs_32
  - if /I "%platform%"=="x64" set HR_TARGET=vs_64
  - if /I "%platform%"=="mingw" set HR_TARGET=mingw
  - if /I "%platform%"=="mingw" set PATH=C:\MinGW\bin;%PATH%
  - if not exist "%LR_EXTERNAL%" (
      mkdir "%LR_EXTERNAL%" &&
      mkdir "%LR_EXTERNAL%\lib" &&
      mkdir "%LR_EXTERNAL%\include"
    )
  - python -m pip install --upgrade pip
  - pip install git+https://github.com/luarocks/hererocks@0.25.0
  - hererocks c:\hererocks --%LUA% --target %HR_TARGET% -rlatest
  - call c:\hererocks\bin\activate

before_build:
  # external deps

build_script:
  - echo "Making..."
  - luarocks install lua-llthreads2
  - luarocks --server=https://luarocks.org/dev install carray
  - luarocks --server=https://luarocks.org/dev install mtmsg
  - luarocks make rockspecs/mtstates-scm-0.rockspec

before_test:
  # test deps

test_script:
  - echo "Testing..."
  - cd %APPVEYOR_BUILD_FOLDER%\tests
  - lua test01.lua
  - lua test02.lua
  - lua test03.lua
  - lua test04.lua
  - lua test05.lua
  - cd %APPVEYOR_BUILD_FOLDER%\examples
  - lua example01.lua
  - lua example02.lua
  - lua example03.lua
  - lua example04.lua
  - lua example05.lua
  - lua example06.lua

after_test:
  # deploy
