local mtstates  = require("mtstates")
local s1 = mtstates.newstate("return function() return 3 end")
local id = s1:id()
local s2 = mtstates.state(id)
local s3 = mtstates.state(id)
assert(s1:isowner() == true)
assert(s2:isowner() == false)
assert(s3:isowner() == false)
s2 = nil
collectgarbage()
assert(s3:call() == 3)
assert(mtstates.state(id):id() == id)
s1 = nil
collectgarbage()
local _, err = pcall(function()
    s3:call()
end)
assert(err:match(mtstates.error.object_closed))
local _, err = pcall(function()
    mtstates.state(id)
end)
assert(err:match(mtstates.error.unknown_object))
