name: test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master

    - name: setup 
      run: |
        luarocks install .github/workflows/lua-llthreads2-0.1.6-1.rockspec
        luarocks --server=https://luarocks.org/dev install mtmsg
        luarocks make rockspecs/mtstates-scm-0.rockspec

    - name: test
      run: |
        set -e
        lua -v
        cd tests
        lua test01.lua
        lua test02.lua
        lua test03.lua
        lua test04.lua
        cd ../examples
        lua example01.lua
        lua example02.lua
        lua example03.lua
        lua example04.lua
        lua example05.lua
        lua example06.lua
     